server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: chat-service
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true


management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: true
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback-spring.xml
mybatis-plus:
#  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      table-underline: true
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
